ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS score INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tier TEXT NOT NULL DEFAULT 'cold' CHECK (tier IN ('vip','engaged','casual','cold')),
  ADD COLUMN IF NOT EXISTS months_active INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_paid_brl NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_paid_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS currently_active BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_leads_score ON leads(list_id, score DESC);

ALTER TABLE lead_lists
  ADD COLUMN IF NOT EXISTS total_vip INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_engaged INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_casual INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_cold INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tier_filter TEXT[] NOT NULL DEFAULT ARRAY['vip','engaged','casual','cold'];
